project_id = "rknheuuyxbvppuxkwhue"

[auth]
site_url = "https://bmvortex.vercel.app"
additional_redirect_urls = [
  "https://bmvortex.vercel.app",
  "https://bmvortex.vercel.app/",
  "https://bmvortex.vercel.app/**",
  "https://bmvortex.vercel.app/reset-password",
  "https://bmvortex.vercel.app/login",
  "https://bmvortex.vercel.app/signup",
  "https://vortexbm-pioyfrbvo-vortexbm.vercel.app",
  "https://vortexbm-pioyfrbvo-vortexbm.vercel.app/",
  "https://vortexbm-pioyfrbvo-vortexbm.vercel.app/**",
  "https://vortexbm-pioyfrbvo-vortexbm.vercel.app/reset-password",
  "https://vortexbm-pioyfrbvo-vortexbm.vercel.app/login",
  "https://vortexbm-pioyfrbvo-vortexbm.vercel.app/signup"
]
jwt_expiry = 3600
enable_signup = true
minimum_password_length = 8

[auth.email]
enable_signup = true
enable_confirmations = true
double_confirm_changes = true
secure_email_change = true

[auth.email.template.confirmation]
subject = "أكّد حسابك في VORTEX"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "إعادة تعيين كلمة المرور — VORTEX"
content_path = "./supabase/templates/recovery.html"
